site:
  name: Tomarac Company Limited
  site: 'https://anzaweb.netlify.app'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Tomarac Company Limited
    template: '%s — Tomarac'
  description: "There's TOMARAC and There's 'Not Exactly'. Multi-sector service provider in Tanzania: Car Rental, Printing & Branding, ICT & Stationery, and Timber Works."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Tomarac Company Limited
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@tomaractz'
    site: '@tomaractz'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
